apiVersion: apps/v1
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# What this is: kubernetes template for Acumos metricbeat deployment
# How to use:
# - Replace fields in <> with actual values (k8s does not support env variables)

kind: Deployment
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: metricbeat
  labels:
    app: metricbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricbeat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metricbeat
    spec:
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: metricbeat
        image: acumos-metricbeat
        imagePullPolicy: IfNotPresent
        env:
        - name: log_level
          value: "DEBUG"
        - name: KIBANA_HOST
          value: "kibana-service"
        - name: KIBANA_PORT
          value: "<ACUMOS_ELK_KIBANA_NODEPORT>"
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch-service"
        - name: ELASTICSEARCH_PORT
          value: "<ACUMOS_ELK_ELASTICSEARCH_PORT>"
        - name: PROCS
          value: ".*"
        - name: PERIOD
          value: "10s"
        - name: SHIPPER_NAME
          value: "acumos-aio"
        ports:
        - containerPort: 8098
        command: ['metricbeat', '-e', '-strict.perms=false', '-system.hostfs=/hostfs']
        volumeMounts:
        - mountPath: /hostfs/proc
          name: proc
          readOnly: true
        - mountPath: /hostfs/sys/fs/cgroup
          name: cgroup
          readOnly: true
        - mountPath: /hostfs
          name: root
          readOnly: true
        - mountPath: /var/run
          name: run
          readOnly: false
        - mountPath: /var/run/docker.sock
          name: sock
# Per https://github.com/elastic/beats/issues/8253
        securityContext:
          privileged: true
      restartPolicy: Always
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: root
        hostPath:
          path: /
      - name: run
        hostPath:
          path: /var/run
      - name: sock
        hostPath:
          path: /var/run/docker.sock
      hostAliases:
      - ip: "<ACUMOS_ELK_HOST>"
        hostnames:
        - "<ACUMOS_ELK_DOMAIN>"
