apiVersion: extensions/v1beta1
# ===============LICENSE_START================================================
# Acumos Apache-2.0
# ============================================================================
# Copyright (C) 2019 Nordix Foundation.
#  ============================================================================
#  This Acumos software file is distributed by Nordix Foundation
#  under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#  This file is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ===============LICENSE_END==================================================
kind: Ingress
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: license-rtu-editor-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - <ACUMOS_DOMAIN>
    secretName: ingress-cert
  rules:
  - host: <ACUMOS_DOMAIN>
    http:
      paths:
      - path: "/license-rtu-editor/"
        backend:
          serviceName: license-rtu-editor-service
          servicePort: 8092
