version: '3.2'
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# What this is: docker-compose template for Acumos kubernetes-client

services:
  nginx:
    image: acumos-docker-proxy
    environment:
      ACUMOS_DOCKER_PROXY_AUTH_API_PORT: 8000
      ACUMOS_DOCKER_PROXY_AUTH_API_PATH: "/auth"
      ACUMOS_AUTH_URL: "http://onboarding-service:8090/onboarding-app/v2/auth/"
      ACUMOS_DOCKER_PROXY_LOG_FILE: "/var/log/acumos/docker-proxy.log"
      ACUMOS_DOCKER_PROXY_LOG_LEVEL: 1
    restart: on-failure
    ports:
      - ${ACUMOS_DOCKER_PROXY_PORT}:8443
    extra_hosts:
      - "${ACUMOS_HOST}:${ACUMOS_HOST_IP}"
    volumes:
      - type: bind
        source: /mnt/${ACUMOS_NAMESPACE}/${ACUMOS_NAMESPACE}/logs
        target: /var/log/acumos
