apiVersion: v1
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# What this is: kubernetes template for Acumos federation service
# How to use:
# - Replace fields in <> with actual values (k8s does not support env variables)

kind: Service
metadata:
  namespace: acumos
  name: federation-service
  labels:
    app: federation
spec:
  selector:
    app: federation
  type: NodePort
  ports:
  - name: federation-gateway
    nodePort: <ACUMOS_FEDERATION_PORT>
    port: 9084
    targetPort: 9084
  - name: federation-local
    port: 9011
    targetPort: 9011

