apiVersion: v1
# ===============LICENSE_START================================================
# Acumos Apache-2.0
# ============================================================================
# Copyright (C) 2019 Nordix Foundation.
#  ============================================================================
#  This Acumos software file is distributed by Nordix Foundation
#  under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#  This file is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ===============LICENSE_END==================================================

# What this is: kubernetes template for Acumos license-profile-editor service
# How to use:

kind: Service
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: license-profile-editor-service
  labels:
    app: license-profile-editor
spec:
  selector:
    app: license-profile-editor
  type: ClusterIP
  ports:
  - name: license-profile-editor-port
    port: 8089
    targetPort: 80
