apiVersion: apps/v1
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# What this is: kubernetes template for Acumos common-data-svc deployment
# How to use:
# - Replace fields in <> with actual values (k8s does not support env variables)

kind: Deployment
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: cds
  labels:
    app: cds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cds
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cds
    spec:
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: cds
        image: <COMMON_DATASERVICE_IMAGE>
        env:
        - name: SPRING_APPLICATION_JSON
          value: '{
                    "server": {
                      "port": 8000
                      },
                    "security": {
                      "user": {
                        "name": "<ACUMOS_CDS_USER>",
                        "password": "<ACUMOS_CDS_PASSWORD>"
                      }
                    },
                    "spring": {
                      "database": {
                        "driver": {
                          "classname": "org.mariadb.jdbc.Driver"
                        }
                      },
                      "datasource": {
                        "url": "jdbc:mysql://<ACUMOS_MARIADB_HOST>:<ACUMOS_MARIADB_PORT>/<ACUMOS_CDS_DB>?useSSL=false",
                        "username": "acumos_opr",
                        "password": "<ACUMOS_MARIADB_USER_PASSWORD>"
                      },
                      "jpa": {
                        "database-platform": "org.hibernate.dialect.MySQLDialect",
                        "hibernate": {
                          "ddl-auto": "validate"
                        }
                      }
                    }
                 }'
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /maven/logs
          name: acumos-logs
      restartPolicy: Always
      volumes:
      - name: acumos-logs
        hostPath:
          path: /var/acumos/logs
      hostAliases:
      - ip: "<ACUMOS_HOST>"
        hostnames:
        - "<ACUMOS_DOMAIN>"
