apiVersion: apps/v1
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# What this is: kubernetes template for Acumos kubernetes-client deployment
# How to use:

kind: Deployment
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: kubernetes-client
  labels:
    app: kubernetes-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubernetes-client
        service: <ACUMOS_DEPLOYMENT_CLIENT_SERVICE_LABEL>
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service
                operator: NotIn
                values:
                - <ACUMOS_DEPLOYMENT_CLIENT_SERVICE_LABEL>
            topologyKey: "kubernetes.io/node"
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: kubernetes-client
        image: <KUBERNETES_CLIENT_IMAGE>
        command: ["/bin/sh", "-c"]
        args:
        - set -x;
          cd maven;
          java $JAVA_OPTS -Dhttp.proxyHost=$ACUMOS_HTTP_PROXY_HOST -Dhttp.proxyPort=$ACUMOS_HTTP_PROXY_PORT -Dhttp.nonProxyHosts=$ACUMOS_HTTP_NON_PROXY_HOSTS -Dhttps.proxyHost=$ACUMOS_HTTP_PROXY_HOST -Dhttps.proxyPort=$ACUMOS_HTTP_PROXY_PORT -Dhttps.nonProxyHosts=$ACUMOS_HTTP_NON_PROXY_HOSTS -Djava.security.egd=file:/dev/./urandom -jar *.jar
        env:
        - name: ACUMOS_HTTP_NON_PROXY_HOSTS
          value: "<ACUMOS_HTTP_NON_PROXY_HOSTS>"
        - name: ACUMOS_HTTP_PROXY_HOST
          value: "<ACUMOS_HTTP_PROXY_HOST>"
        - name: ACUMOS_HTTP_PROXY_PORT
          value: "<ACUMOS_HTTP_PROXY_PORT>"
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx512m"
        - name: SPRING_APPLICATION_JSON
          value: '{
            "logging": {
              "level": {
                "root": "INFO"
              }
            },
            "kube" : {
              "incrementPort": "8557",
              "singleModelPort": "8556",
              "folderPath": "/maven/home",
              "singleNodePort": "30333",
              "singleTargetPort": "3330",
              "dataBrokerModelPort": "8556",
              "dataBrokerNodePort": "30556",
              "dataBrokerTargetPort": "8556",
              "mlTargetPort": "3330",
              "nginxImageName": "nginx",
              "nexusEndPointURL": "http://localhost:80"
            },
            "dockerproxy": {
            "host": "<ACUMOS_DOCKER_PROXY_HOST>",
            "port": "<ACUMOS_DOCKER_PROXY_PORT>"
            },
            "blueprint": {
              "ImageName": "<BLUEPRINT_ORCHESTRATOR_IMAGE>",
              "name": "blueprint-orchestrator",
              "nodePort": "30555",
              "port": "8555"
            },
            "nexus": {
              "url": "http://<ACUMOS_NEXUS_HOST>:<ACUMOS_NEXUS_API_PORT>/<ACUMOS_NEXUS_MAVEN_REPO_PATH>/<ACUMOS_NEXUS_MAVEN_REPO>/",
              "password": "<ACUMOS_NEXUS_RW_USER_PASSWORD>",
              "username": "<ACUMOS_NEXUS_RW_USER>",
              "groupid": "<ACUMOS_NEXUS_GROUP>"
            },
            "cmndatasvc": {
              "cmndatasvcendpointurl": "http://<ACUMOS_CDS_HOST>:<ACUMOS_CDS_PORT>/ccds",
              "cmndatasvcuser": "<ACUMOS_CDS_USER>",
              "cmndatasvcpwd": "<ACUMOS_CDS_PASSWORD>"
            },
            "probe": {
              "probeImageName": "<PROTO_VIEWER_IMAGE>",
              "probeImagePORT": "5006",
              "probeModelPort": "5006",
              "probeNodePort": "30800",
              "probeTargetPort": "5006",
              "probeApiPort": "5006",
              "probeExternalPort": "30800",
              "probeSchemaPort": "80"
            },
            "logstash": {
              "host": "<ACUMOS_ELK_HOST>",
              "ip": "<ACUMOS_ELK_HOST_IP>",
              "port": "<ACUMOS_ELK_LOGSTASH_PORT>"
            }
          }'
        ports:
        - containerPort: 8082
        volumeMounts:
        - mountPath: /maven/logs
          name: logs
      restartPolicy: Always
      volumes:
      - name: logs
        persistentVolumeClaim:
         claimName: <ACUMOS_DEPLOYMENT_LOGS_PVC_NAME>
