apiVersion: apps/v1
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# What this is: kubernetes template for Acumos security-verification scanning
# service deployment

kind: Deployment
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: sv-scanning
  labels:
    app: sv-scanning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sv-scanning
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sv-scanning
    spec:
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: sv-scanning
        image: <SECURITY_VERIFICATION_IMAGE>
        securityContext:
          privileged: true
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: JAVA_OPTS
          value: "-Xms128m -Xmx256m"
        - name: ACUMOS_ADMIN_USER
          value: "admin"
        - name: ACUMOS_CDS_HOST
          value: "cds-service"
        - name: ACUMOS_CDS_PORT
          value: "8000"
        - name: ACUMOS_CDS_USER
          value: "<ACUMOS_CDS_USER>"
        - name: ACUMOS_CDS_PASSWORD
          value: "<ACUMOS_CDS_PASSWORD>"
        - name: ACUMOS_NEXUS_HOST
          value: "<ACUMOS_NEXUS_HOST>"
        - name: ACUMOS_NEXUS_API_PORT
          value: "<ACUMOS_NEXUS_API_PORT>"
        - name: ACUMOS_NEXUS_MAVEN_REPO
          value: "<ACUMOS_NEXUS_MAVEN_REPO>"
        - name: SPRING_APPLICATION_JSON
          value: '{
            "logging": {
              "level": {
                "root": "INFO"
              }
            },
            "server" : {
              "port" : 9082
            },
            "cdms": {
              "client": {
                "url": "http://cds-service:8000/ccds",
                "username": "<ACUMOS_CDS_USER>",
                "password": "<ACUMOS_CDS_PASSWORD>",
                "host": "cds-service",
                "port": "8000"
              }
            },
            "nexus": {
              "client": {
                "url": "http://<ACUMOS_NEXUS_HOST>:<ACUMOS_NEXUS_API_PORT>/<ACUMOS_NEXUS_MAVEN_REPO_PATH>/<ACUMOS_NEXUS_MAVEN_REPO>/",
                "proxy": "",
                "password": "<ACUMOS_NEXUS_RW_USER_PASSWORD>",
                "username": "<ACUMOS_NEXUS_RW_USER>",
                "groupId": "<ACUMOS_NEXUS_GROUP>"
              }
            },
            "siteConfig": "{ \"verification\": {
                \"externalScan\": \"false\",
                \"allowedLicense\": [
                  { \"type\": \"SPDX\", \"value\": \"Apache-2.0\" },
                  { \"type\": \"SPDX\", \"value\": \"CC-BY-4.0\" },
                  { \"type\": \"SPDX\", \"value\": \"BSD-3-Clause\" },
                  { \"type\": \"VendorA\", \"value\": \"Vendor-A-OSS\" },
                  { \"type\": \"CompanyB\", \"value\": \"Company-B-Proprietary\" }
                ],
                \"compatibleLicenses\":[
                  { \"name\":\"Apache-2.0\", \"compatible\":[
                      { \"name\":\"CC-BY-4.0\" },
                      { \"name\":\"Apache-2.0\" },
                      { \"name\":\"BSD-3-Clause\" },
                      { \"name\":\"MIT-License\" }
                    ]
                  },
                  { \"name\":\"BSD-3-Clause\", \"compatible\":[
                      { \"name\":\"CC-BY-4.0\" },
                      { \"name\":\"Apache-2.0\" },
                      { \"name\":\"BSD-3-Clause\" },
                      { \"name\":\"MIT-License\" }
                    ]
                  },
                  { \"name\":\"MIT-License\", \"compatible\":[
                      { \"name\":\"CC-BY-4.0\" },
                      { \"name\":\"Apache-2.0\" },
                      { \"name\":\"BSD-3-Clause\" },
                      { \"name\":\"MIT-License\" }
                    ]
                  },
                  { \"name\":\"Vendor-A-OSS\", \"compatible\":[
                      { \"name\":\"Vendor-A-OSS\" },
                      { \"name\":\"CC-BY-4.0\" },
                      { \"name\":\"Apache-2.0\" },
                      { \"name\":\"BSD-3-Clause\" },
                      { \"name\":\"MIT-License\" }
                    ]
                  },
                  { \"name\":\"Company-B-Proprietary\", \"compatible\":[
                      { \"name\":\"Company-B-Proprietary\" },
                      { \"name\":\"CC-BY-4.0\" },
                      { \"name\":\"Apache-2.0\" },
                      { \"name\":\"BSD-3-Clause\" },
                      { \"name\":\"MIT-License\" }
                    ]
                  }
                ],
                \"licenseScan\": {
                  \"created\": \"true\",
                  \"updated\": \"true\",
                  \"deploy\": \"false\",
                  \"download\": \"false\",
                  \"share\": \"false\",
                  \"publishCompany\": \"false\",
                  \"publishPublic\": \"false\"
                },
                \"securityScan\": {
                  \"created\": \"true\",
                  \"updated\": \"true\",
                  \"deploy\": \"false\",
                  \"download\": \"false\",
                  \"share\": \"false\",
                  \"publishCompany\": \"false\",
                  \"publishPublic\": \"false\"
                },
                \"licenseVerify\": {
                  \"deploy\": \"true\",
                  \"download\": \"true\",
                  \"share\": \"false\",
                  \"publishCompany\": \"true\",
                  \"publishPublic\": \"true\"
                },
                \"securityVerify\": {
                  \"deploy\": \"true\",
                  \"download\": \"true\",
                  \"share\": \"false\",
                  \"publishCompany\": \"true\",
                  \"publishPublic\": \"true\"
                }
              }
            }"
          }'
        command: ["/bin/bash", "/maven/scan/setup.sh"]
        ports:
        - containerPort: 9082
        volumeMounts:
        - mountPath: /maven/logs
          name: logs
        - mountPath: /maven/conf/scripts
          name: scripts
        - mountPath: /maven/conf/licenses
          name: licenses
        - mountPath: /maven/conf/rules
          name: rules
      restartPolicy: Always
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: <ACUMOS_LOGS_PVC_NAME>
      - name: scripts
        configMap:
          name: sv-scanning-scripts
      - name: licenses
        configMap:
          name: sv-scanning-licenses
      - name: rules
        configMap:
          name: sv-scanning-rules
      hostAliases:
      - ip: "<ACUMOS_HOST_IP>"
        hostnames:
        - "<ACUMOS_HOST>"
