apiVersion: apps/v1
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# What this is: kubernetes template for Acumos security-verification scanning
# service deployment

kind: Deployment
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: sv-scanning
  labels:
    app: sv-scanning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sv-scanning
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sv-scanning
        service: <ACUMOS_SECURITY_VERIFICATION_SERVICE_LABEL>
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service
                operator: NotIn
                values:
                - <ACUMOS_SECURITY_VERIFICATION_SERVICE_LABEL>
            topologyKey: "kubernetes.io/node"
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: sv-scanning
        image: <SECURITY_VERIFICATION_IMAGE>
        securityContext:
          privileged: <ACUMOS_PRIVILEGED_ENABLE>
        env:
        - name: SPRING_APPLICATION_JSON
          value: '{
            "logging": {
              "level": {
                "root": "INFO"
              }
            },
            "server" : {
              "port" : 9082
            },
            "cdms": {
              "client": {
                "url": "http://cds-service:8000/ccds",
                "username": "<ACUMOS_CDS_USER>",
                "password": "<ACUMOS_CDS_PASSWORD>",
                "host": "cds-service",
                "port": "8000"
              }
            },
            "nexus": {
              "client": {
                "url": "http://<ACUMOS_NEXUS_HOST>:<ACUMOS_NEXUS_API_PORT>/<ACUMOS_NEXUS_MAVEN_REPO_PATH>/<ACUMOS_NEXUS_MAVEN_REPO>/",
                "proxy": "",
                "password": "<ACUMOS_NEXUS_RW_USER_PASSWORD>",
                "username": "<ACUMOS_NEXUS_RW_USER>",
                "groupId": "<ACUMOS_NEXUS_GROUP>"
              }
            },
            "jenkins": {
              "client": {
                "url": "<ACUMOS_JENKINS_API_URL>",
                "user": "<ACUMOS_JENKINS_USER>",
                "password": "<ACUMOS_JENKINS_PASSWORD>",
                "scanJob": "<ACUMOS_JENKINS_SCAN_JOB>"
              }
            },
            "siteConfig": "{
              \"externalScan\": \"<ACUMOS_SECURITY_VERIFICATION_EXTERNAL_SCAN>\",
              \"allowedLicense\": [
                { \"type\": \"SPDX\", \"name\": \"Apache-2.0\", \"rtuRequired\": \"false\" },
                { \"type\": \"SPDX\", \"name\": \"CC-BY-4.0\", \"rtuRequired\": \"false\" },
                { \"type\": \"SPDX\", \"name\": \"BSD-3-Clause\", \"rtuRequired\": \"false\" },
                { \"type\": \"VendorA\", \"name\": \"Vendor-A-OSS\", \"rtuRequired\": \"false\" },
                { \"type\": \"CompanyB\", \"name\": \"Company-B-Proprietary\", \"rtuRequired\": \"true\" }
              ],
              \"compatibleLicenses\":[
                { \"name\":\"Apache-2.0\", \"compatible\":[
                    { \"name\":\"CC-BY-4.0\" },
                    { \"name\":\"Apache-2.0\" },
                    { \"name\":\"BSD-3-Clause\" },
                    { \"name\":\"MIT-License\" }
                  ]
                },
                { \"name\":\"BSD-3-Clause\", \"compatible\":[
                    { \"name\":\"CC-BY-4.0\" },
                    { \"name\":\"Apache-2.0\" },
                    { \"name\":\"BSD-3-Clause\" },
                    { \"name\":\"MIT-License\" }
                  ]
                },
                { \"name\":\"MIT-License\", \"compatible\":[
                    { \"name\":\"CC-BY-4.0\" },
                    { \"name\":\"Apache-2.0\" },
                    { \"name\":\"BSD-3-Clause\" },
                    { \"name\":\"MIT-License\" }
                  ]
                },
                { \"name\":\"Vendor-A-OSS\", \"compatible\":[
                    { \"name\":\"Vendor-A-OSS\" },
                    { \"name\":\"CC-BY-4.0\" },
                    { \"name\":\"Apache-2.0\" },
                    { \"name\":\"BSD-3-Clause\" },
                    { \"name\":\"MIT-License\" }
                  ]
                },
                { \"name\":\"Company-B-Proprietary\", \"compatible\":[
                    { \"name\":\"Company-B-Proprietary\" },
                    { \"name\":\"CC-BY-4.0\" },
                    { \"name\":\"Apache-2.0\" },
                    { \"name\":\"BSD-3-Clause\" },
                    { \"name\":\"MIT-License\" }
                  ]
                }
              ],
              \"licenseScan\": {
                \"created\": \"true\",
                \"updated\": \"true\",
                \"deploy\": \"false\",
                \"download\": \"false\",
                \"share\": \"false\",
                \"publishCompany\": \"false\",
                \"publishPublic\": \"false\"
              },
              \"securityScan\": {
                \"created\": \"true\",
                \"updated\": \"true\",
                \"deploy\": \"false\",
                \"download\": \"false\",
                \"share\": \"false\",
                \"publishCompany\": \"false\",
                \"publishPublic\": \"false\"
              },
              \"licenseVerify\": {
                \"deploy\": \"true\",
                \"download\": \"true\",
                \"share\": \"false\",
                \"publishCompany\": \"true\",
                \"publishPublic\": \"true\"
              },
              \"securityVerify\": {
                \"deploy\": \"true\",
                \"download\": \"true\",
                \"share\": \"false\",
                \"publishCompany\": \"true\",
                \"publishPublic\": \"true\"
              }
            }"
          }'
        ports:
        - containerPort: 9082
        volumeMounts:
        - mountPath: /maven/logs
          name: logs
        - mountPath: /maven/certs
          name: certs-volume
      restartPolicy: Always
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: <ACUMOS_COMMON_LOGS_PVC_NAME>
      - name: certs-volume
        configMap:
          name: acumos-certs
