version: '3.2'
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# docker-compose for nexus
#
# Notes:
# Ports are exposed since it's assumed that nexus service may be deployed
# outside the acumos docker/k8s cluster, thus a nodeport-range (30000-32767)
# port may be allocated. For the docker model port, this external port must
# map to an internal port of the same value, since that is how the docker client
# will connect to the docker repository (using the extrernal port #)

services:
   nexus-service:
       image: sonatype/nexus3:3.9.0
       environment:
           log_level: "DEBUG"
       ports:
           - ${ACUMOS_NEXUS_API_PORT}:8081
           - ${ACUMOS_DOCKER_MODEL_PORT}:${ACUMOS_DOCKER_MODEL_PORT}
       volumes:
           - type: bind
             source: /var/${ACUMOS_NAMESPACE}/logs
             target: /maven/logs
           - type: bind
             source: /var/${ACUMOS_NAMESPACE}/nexus-data
             target: /nexus-data
       logging:
           driver: json-file
       extra_hosts:
           - "${ACUMOS_HOST}:${ACUMOS_HOST_IP}"
       restart: on-failure

