# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2018-2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appVersion: "1.0.0"

namespace: "<ACUMOS_ELK_NAMESPACE>"
clusterName: "k8-cluster-elk"

elasticsearch:
  image:
    repository: "<ACUMOS_RELEASE>/acumos-elasticsearch"
    tag: "2.2.2"
    pullPolicy: "IfNotPresent"

  port: <ACUMOS_ELK_ELASTICSEARCH_PORT>
  indexPort: <ACUMOS_ELK_ELASTICSEARCH_INDEX_PORT>

  persistence:
    enabled: true
    pvcName: "<ACUMOS_ELASTICSEARCH_DATA_PVC_NAME>"
    pvName: "<ACUMOS_ELASTICSEARCH_DATA_PV_NAME>"
    size: "10Gi"

  resources:
    limits:
      cpu: "750m"
      memory: "6Gi"
    requests:
      cpu: "750m"
      memory: "4Gi"

  nodeAffinity: {}
  nodeSelector: {}
  tolerations: []

logstash:
  image:
    repository: "<ACUMOS_RELEASE>/acumos-logstash"
    tag: "2.2.2"
    pullPolicy: "IfNotPresent"
  port: "<ACUMOS_ELK_LOGSTASH_PORT>"

kibana:
  image:
    repository: "<ACUMOS_RELEASE>/acumos-kibana"
    tag: "2.2.2"
    pullPolicy: "IfNotPresent"
  port: "<ACUMOS_ELK_KIBANA_PORT>"
