version: '3.2'
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# docker-compose for Acumos logging component filebeat
#
services:
  filebeat-service:
    image: acumos-filebeat
    volumes:
      - type: bind
        source: /var/${ACUMOS_NAMESPACE}/logs
        target: /filebeat-logs
    environment:
      - LOGSTASH_HOST=${ACUMOS_ELK_DOMAIN}
      - LOGSTASH_PORT=${ACUMOS_ELK_LOGSTASH_PORT}
    extra_hosts:
      - "${ACUMOS_ELK_DOMAIN}:${ACUMOS_ELK_HOST}"
    restart: on-failure
