apiVersion: v1
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# What this is: kubernetes template for Acumos portal-fe service
# How to use:
# - Replace fields in <> with actual values (k8s does not support env variables)

kind: Service
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: mariadb-service
  labels:
    app: mariadb-service
spec:
  selector:
    app: mariadb-service
  type: NodePort
  ports:
  - name: mariadb
    nodePort: <ACUMOS_MARIADB_NODEPORT>
    port: 3306
    targetPort: 3306
  - name: mariadb-adminer
    nodePort: <ACUMOS_MARIADB_ADMINER_NODEPORT>
    port: 8080
    targetPort: 8080
