version: '3.2'
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# docker-compose for ds-compositionengine
# TODO: scrub all attributes for current need
services:
   dsce-service:
       image: ${DESIGNSTUDIO_IMAGE}
       environment:
           SPRING_APPLICATION_JSON: "{
                          \"server\": {
                                \"port\": ${ACUMOS_DSCE_PORT}
                          },
                          \"dateformat\": \"yyyy-MM-dd-HH-mm-ss-SSS\",
                          \"solutionResultsetSize\": \"2000\",
                          \"cdsCheckInterval\": 10000,
                          \"cdsCheckAttempt\": 4,
                          \"imagedatabrokerURI\": \"${DATABROKER_ZIPBROKER_IMAGE}\",
                          \"csvdatabrokerURI\": \"${DATABROKER_CSVBROKER_IMAGE}\",
                          \"sqldatabrokerURI\": \"${DATABROKER_SQLBROKER_IMAGE}\",
                          \"jsondatabrokerURI\": \"NA\",
                          \"sqldatabrokerURI\": \"NA\",
                          \"lib\": \"/maven/\",
                          \"tosca\": {
                                \"outputfolder\": \"/temp/output/\"
                          },
                          \"nexus\": {
                                \"nexusendpointurl\": \"http://${ACUMOS_NEXUS_HOST}:${ACUMOS_NEXUS_API_PORT}/repository/acumos_model_maven/\",
                                \"nexusproxy\": \"\",
                                \"nexuspassword\": \"${ACUMOS_NEXUS_RW_USER_PASSWORD}\",
                                \"nexususername\": \"${ACUMOS_NEXUS_RW_USER}\",
                                \"nexusgroupid\": \"com.artifact\"
                          },
                          \"cmndatasvc\": {
                                \"cmndatasvcendpoinurl\": \"http://cds-service:${ACUMOS_CDS_PORT}/ccds\",
                                \"cmndatasvcuser\": \"${ACUMOS_CDS_USER}\",
                                \"cmndatasvcpwd\": \"${ACUMOS_CDS_PASSWORD}\"
                          },
                          \"docker\": {
                                \"host\": \"${ACUMOS_DOCKER_API_HOST}\",
                                \"port\": \"${ACUMOS_DOCKER_API_PORT}\",
                                \"config\": \"/docker_host/.docker\",
                                \"registry\": {
                                        \"url\": \"http://${ACUMOS_NEXUS_HOST}:${ACUMOS_DOCKER_MODEL_PORT}/\",
                                        \"username\": \"${ACUMOS_NEXUS_RW_USER}\",
                                        \"password\": \"${ACUMOS_NEXUS_RW_USER_PASSWORD}\",
                                        \"email\": \"${ACUMOS_ADMIN_EMAIL}\"
                                            },
                                \"tls\": {\"verify\": \"false\"},
                                \"api\": {\"version\": \"1.23\"},
                                \"imagetag\": {
                                        \"prefix\": \"${ACUMOS_NEXUS_HOST}:${ACUMOS_DOCKER_MODEL_PORT}\"
                                            },
                                \"max_total_connections\": \"1\",
                                \"max_per_route_connections\": \"1\"
                            }
                        }"
       expose:
           - ${ACUMOS_DSCE_PORT}
       volumes:
           - type: bind
             source: /var/${ACUMOS_NAMESPACE}/logs
             target: /maven/logs
           - type: bind
             source: /var/${ACUMOS_NAMESPACE}/output
             target: /temp/
       logging:
           driver: json-file
       extra_hosts:
           - "${ACUMOS_DOMAIN}:${ACUMOS_HOST}"
       restart: on-failure
