version: '3.2'
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# docker-compose for security-verification service

services:
    sv-scanning-service:
        image: ${SECURITY_VERIFICATION_IMAGE}
        environment:
            ACUMOS_ADMIN_USER: "admin"
            ACUMOS_CDS_HOST: "cds-service"
            ACUMOS_CDS_PORT: "8000"
            ACUMOS_CDS_USER: "${ACUMOS_CDS_USER}"
            ACUMOS_CDS_PASSWORD: "${ACUMOS_CDS_PASSWORD}"
            ACUMOS_NEXUS_HOST: "${ACUMOS_NEXUS_HOST}"
            ACUMOS_NEXUS_API_PORT: "${ACUMOS_NEXUS_API_PORT}"
            ACUMOS_NEXUS_MAVEN_REPO: "${ACUMOS_NEXUS_MAVEN_REPO}"
            SPRING_APPLICATION_JSON: "{
              \"server\" : {
                 \"port\" : 9082
              },
              \"cdms\": {
              \"client\": {
                \"url\": \"http://cds-service:8000/ccds\",
                \"username\": \"${ACUMOS_CDS_USER}\",
                \"password\": \"${ACUMOS_CDS_PASSWORD}\"
              }
              },
              \"nexus\": {
                \"groupId\": \"com.artifact\",
                \"client\": {
                  \"url\": \"http://${ACUMOS_NEXUS_HOST}:${ACUMOS_NEXUS_API_PORT}/${ACUMOS_NEXUS_MAVEN_REPO_PATH}/${ACUMOS_NEXUS_MAVEN_REPO}/\",
                  \"proxy\": \"\",
                  \"password\": \"${ACUMOS_NEXUS_RW_USER_PASSWORD}\",
                  \"username\": \"${ACUMOS_NEXUS_RW_USER}\",
                  \"groupId\": \"com.artifact\"
                }
              },
              \"siteConfig\": {
                \"configValue\": \"{
                    \\\"verification\\\": {
                    \\\"externalScan\\\": \\\"false\\\",
                    \\\"allowedLicense\\\": [
                      { \\\"type\\\": \\\"SPDX\\\", \\\"value\\\": \\\"Apache-2.0\\\" },
                      { \\\"type\\\": \\\"SPDX\\\", \\\"value\\\": \\\"CC-BY-4.0\\\" },
                      { \\\"type\\\": \\\"SPDX\\\", \\\"value\\\": \\\"BSD-3-Clause\\\" },
                      { \\\"type\\\": \\\"VendorA\\\", \\\"value\\\": \\\"VendorA-OSS\\\" },
                      { \\\"type\\\": \\\"CompanyB\\\", \\\"value\\\": \\\"CompanyB-Proprietary\\\" }
                    ],
                    \\\"licenseScan\\\": {
                      \\\"created\\\": \\\"true\\\",
                      \\\"updated\\\": \\\"true\\\",
                      \\\"deploy\\\": \\\"false\\\",
                      \\\"download\\\": \\\"false\\\",
                      \\\"share\\\": \\\"false\\\",
                      \\\"publishCompany\\\": \\\"false\\\",
                      \\\"publishPublic\\\": \\\"false\\\"
                    },
                    \\\"securityScan\\\": {
                      \\\"created\\\": \\\"true\\\",
                      \\\"updated\\\": \\\"true\\\",
                      \\\"deploy\\\": \\\"false\\\",
                      \\\"download\\\": \\\"false\\\",
                      \\\"share\\\": \\\"false\\\",
                      \\\"publishCompany\\\": \\\"false\\\",
                      \\\"publishPublic\\\": \\\"false\\\"
                    },
                    \\\"licenseVerify\\\": {
                      \\\"deploy\\\": \\\"true\\\",
                      \\\"download\\\": \\\"true\\\",
                      \\\"share\\\": \\\"false\\\",
                      \\\"publishCompany\\\": \\\"true\\\",
                      \\\"publishPublic\\\": \\\"true\\\"
                    },
                    \\\"securityVerify\\\": {
                      \\\"deploy\\\": \\\"true\\\",
                      \\\"download\\\": \\\"true\\\",
                      \\\"share\\\": \\\"false\\\",
                      \\\"publishCompany\\\": \\\"true\\\",
                      \\\"publishPublic\\\": \\\"true\\\"
                    }
                  }
                }\"
              }
            }"
        expose:
            - 9082
        ports:
            - ${ACUMOS_SECURITY_VERIFICATION_PORT}:9082
        volumes:
            - type: bind
              source: /mnt/${ACUMOS_NAMESPACE}/logs
              target: /maven/logs
        logging:
            driver: json-file
        extra_hosts:
            - "${ACUMOS_HOST}:${ACUMOS_HOST_IP}"
        restart: on-failure
