# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: mlwb-project-webcomponent
  labels:
    app: mlwb-project-webcomponent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlwb-project-webcomponent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mlwb-project-webcomponent
        service: <ACUMOS_MLWB_SERVICE_LABEL>
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: service
                operator: NotIn
                values:
                - <ACUMOS_MLWB_SERVICE_LABEL>
            topologyKey: "kubernetes.io/node"
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: mlwb-project-webcomponent
        image: <MLWB_PROJECT_WEBCOMPONENT_IMAGE>
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms128m -Xmx256m"
        - name: ENVIRONMENT
          value: "deploy"
        - name: PORT
          value: "9084"
        - name: projectmSURL
          value: "http://mlwb-project-service:9088/mlWorkbench/v1/project"
        - name: notebookmSURL
          value: "http://mlwb-notebook-service:9089/mlWorkbench/v1/notebook"
        - name: pipelinemSURL
          value: "http://mlwb-pipeline-service:9090/mlWorkbench/v1/pipeline"
        - name: predictormSURL
          value: "http://mlwb-predictor-service:9096/mlWorkbench/v1/predictor"
        - name: projectWikiURL
          value: "https://wiki.acumos.org/display/TRAIN"
        - name: notebookWikiURL
          value: "https://wiki.acumos.org/display/TRAIN"
        - name: pipelineWikiURL
          value: "https://wiki.acumos.org/display/TRAIN"
        - name: predictorWikiURL
          value: "https://wiki.acumos.org/display/TRAIN"
        - name: pipelineFlag
          value: "true"
        - name: createTimeout
          value: "60000"
        - name: modelmSURL
          value: "http://mlwb-model-service:9093/mlWorkbench/v1/modelservice"
        - name: modelWikiURL
          value: "http://wiki.acumos.org/display/TRAIN"
        - name: portalFEURL
          value: "https://<ACUMOS_DOMAIN>"
        - name: portalBEURL
          value: "http://portal-be-service:8083"
        - name: useExternalNotebook
          value: "true"
        - name: useExternalPipeline
          value: "true"
        ports:
        - containerPort: 9084
        volumeMounts:
        - mountPath: /maven/logs
          name: logs
      restartPolicy: Always
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: <ACUMOS_MLWB_LOGS_PVC_NAME>
