# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: mlwb-home-webcomponent
  labels:
    app: mlwb-home-webcomponent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlwb-home-webcomponent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mlwb-home-webcomponent
    spec:
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: mlwb-home-webcomponent
        image: <MLWB_HOME_WEBCOMPONENT_IMAGE>
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms128m -Xmx256m"
        - name: ENVIRONMENT
          value: "deploy"
        - name: dashboardComponent
          value: "https://<ACUMOS_DOMAIN>/mlwb-dashboard-webcomponent"
        - name: projectComponent
          value: "https://<ACUMOS_DOMAIN>/mlwb-project-webcomponent"
        - name: projectCatalogComponent
          value: "https://<ACUMOS_DOMAIN>/mlwb-project-catalog-webcomponent"
        - name: notebookComponent
          value: "https://<ACUMOS_DOMAIN>/mlwb-notebook-webcomponent"
        - name: notebookCatalogComponent
          value: "https://<ACUMOS_DOMAIN>/mlwb-notebook-catalog-webcomponent"
        - name: pipelineComponent
          value: "https://<ACUMOS_DOMAIN>/mlwb-pipeline-webcomponent"
        - name: pipelineCatalogComponent
          value: "https://<ACUMOS_DOMAIN>/mlwb-pipeline-catalog-webcomponent"
        - name: portalFEURL
          value: "https://<ACUMOS_DOMAIN>"
        - name: menuItems
          value: '[
            {
            "title": "Dashboard",
            "icon": "fa fa-tachometer-alt",
            "link": "/pages/dashboard", "home": true
            },
            {
            "title": "Projects",
            "icon": "fa fa-project-diagram",
            "link": "/pages/projects/catalog"
            },
            {
            "title": "Notebooks",
            "icon": "fas fa-book-open",
            "link": "/pages/notebook/catalog"
            },
            {
            "title": "Data Pipelines",
            "icon": "fa fa-code-branch",
            "link": "/pages/pipeline/catalog"
            },
            {
            "title": "AcuCompose",
            "icon": "fas fa-crop-alt",
            "link": "/pages/acuCompose"
            }
          ]'
        ports:
        - containerPort: 9082
        volumeMounts:
        - mountPath: /maven/logs
          name: logs
      restartPolicy: Always
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: <ACUMOS_LOGS_PVC_NAME>
      hostAliases:
      - ip: "<ACUMOS_HOST_IP>"
        hostnames:
        - "<ACUMOS_HOST>"
