# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: mlwb-pipeline
  labels:
    app: mlwb-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlwb-pipeline
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mlwb-pipeline
    spec:
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: mlwb-pipeline
        image: <MLWB_PIPELINE_SERVICE_IMAGE>
        env:
        - name: ACUMOS_NAMESPACE
          value: <ACUMOS_NAMESPACE>
        - name: TRUSTSTORE_PASSWORD
          value: <MLWB_NIFI_TRUSTSTORE_PASSWORD>
        - name: KEYSTORE_PASSWORD
          value: <MLWB_NIFI_KEYSTORE_PASSWORD>
        - name: SPRING_APPLICATION_JSON
          value: '{
            "server": {
              "port": 9090
            },
            "dateformat": "yyyy-MM-dd-HH-mm-ss-SSS",
            "resultsetSize": 2000,
            "cmndatasvc": {
              "url": "http://cds-service:8000/ccds",
              "user": "<ACUMOS_CDS_USER>",
              "pwd": "<ACUMOS_CDS_PASSWORD>"
            },
            "projectservice": {
              "url": "http://mlwb-project-service:9088/mlWorkbench/v1/project"
            },
            "jwt" : {
              "secretkey": "<ACUMOS_JWT_KEY>"
            },
            "maxtries": 5,
            "sleeptimems": 30000,
            "nifi": {
              "waittime": "90000",
              "createpod": true,
              "adminusername" : "<MLWB_NIFI_REGISTRY_INITIAL_ADMIN>",
              "serviceurl": "http://nifi-service-{0}:8080",
              "registryurl": "http://nifi-registry-service:8080",
              "directregistryurl": "https://<MLWB_NIFI_REGISTRY_INITIAL_ADMIN_NAME>:8443",
              "registryname": "Acumos-NiFi-Registry",
              "namespace": "<ACUMOS_NAMESPACE>",
              "template": {
                "path": "/maven/templates/",
                "apacheconfigmap": "apache_configmap.yaml",
                "nificonfigmap": "nifi_configmap.yaml",
                "service": "service.yaml",
                "serviceadmin": "service_admin.yaml",
                "ingress": "ingress.yaml",
                "deployment": "deployment.yaml"
              }
            }
          }'
        command: ["/bin/bash", "-c"]
        args:
        - if [[ ! -d /maven/templates ]]; then
            mkdir /maven/templates;
          fi;
          cp /maven/temp/* /maven/templates/.;
          chmod 777 /maven/templates/*;
          cd /maven;
          java -Xms128m -Xmx512m -Djava.security.egd=file:/dev/./urandom -jar pipeline-service-*jar;
        ports:
        - containerPort: 9090
        volumeMounts:
        - mountPath: /maven/logs
          name: logs
        - mountPath: /maven/conf
          name: nifi-certs-registry
        - mountPath: /maven/temp
          name: nifi-templates
      restartPolicy: Always
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: pvc-<ACUMOS_NAMESPACE>-logs
      - name: nifi-certs-registry
        secret:
          secretName: nifi-certs-registry
      - name: nifi-templates
        configMap:
          name: nifi-templates
      hostAliases:
      - ip: "<ACUMOS_HOST_IP>"
        hostnames:
        - "<ACUMOS_HOST>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: mlwb-pipeline-webcomponent
  labels:
    app: mlwb-pipeline-webcomponent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlwb-pipeline-webcomponent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mlwb-pipeline-webcomponent
    spec:
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: mlwb-pipeline-webcomponent
        image: <MLWB_PIPELINE_WEBCOMPONENT_IMAGE>
        env:
        - name: ES_JAVA_OPTS
          value: "-Xmx256m -Xms256m"
        - name: ENVIRONMENT
          value: "deploy"
        - name: pipelinemSURL
          value: "http://mlwb-pipeline-service:9090/mlWorkbench/v1/pipeline"
        - name: pipelineWikiURL
          value: "https://wiki.acumos.org/display/TRAIN"
        ports:
        - containerPort: 9091
        volumeMounts:
        - mountPath: /maven/logs
          name: logs
      restartPolicy: Always
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: pvc-<ACUMOS_NAMESPACE>-logs
      hostAliases:
      - ip: "<ACUMOS_HOST_IP>"
        hostnames:
        - "<ACUMOS_HOST>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: mlwb-pipeline-catalog-webcomponent
  labels:
    app: mlwb-pipeline-catalog-webcomponent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlwb-pipeline-catalog-webcomponent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mlwb-pipeline-catalog-webcomponent
    spec:
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: mlwb-pipeline-catalog-webcomponent
        image: <MLWB_PIPELINE_CATALOG_WEBCOMPONENT_IMAGE>
        env:
        - name: ES_JAVA_OPTS
          value: "-Xmx256m -Xms256m"
        - name: ENVIRONMENT
          value: "deploy"
        - name: projectmSURL
          value: "http://mlwb-project-service:9088/mlWorkbench/v1/project"
        - name: notebookmSURL
          value: "http://mlwb-notebook-service:9089/mlWorkbench/v1/notebook"
        - name: pipelinemSURL
          value: "http://mlwb-pipeline-service:9090/mlWorkbench/v1/pipeline"
        - name: notebookWikiURL
          value: "https://wiki.acumos.org/display/TRAIN"
        ports:
        - containerPort: 9092
        volumeMounts:
        - mountPath: /maven/logs
          name: logs
      restartPolicy: Always
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: pvc-<ACUMOS_NAMESPACE>-logs
      hostAliases:
      - ip: "<ACUMOS_HOST_IP>"
        hostnames:
        - "<ACUMOS_HOST>"
